// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// PingParams is parameters of Ping operation.
type PingParams struct {
	Message OptString
}

func unpackPingParams(packed middleware.Parameters) (params PingParams) {
	{
		key := middleware.ParameterKey{
			Name: "message",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Message = v.(OptString)
		}
	}
	return params
}

func decodePingParams(args [0]string, argsEscaped bool, r *http.Request) (params PingParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: message.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "message",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMessageVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotMessageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Message.SetTo(paramsDotMessageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
