// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListJob implements ListJob operation.
	//
	// List jobs.
	//
	// GET /api/job
	ListJob(ctx context.Context) (ListJobRes, error)
	// Ping implements Ping operation.
	//
	// Ping server.
	//
	// GET /api/ping
	Ping(ctx context.Context, params PingParams) (PingRes, error)
	// RunJob implements RunJob operation.
	//
	// Run a job.
	//
	// POST /api/job/run
	RunJob(ctx context.Context, req *RunJobRequest) (RunJobRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
