// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/ApiErrorAuthError
type ApiErrorAuthError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiErrorAuthError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiErrorAuthError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiErrorAuthError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiErrorAuthError) SetMessage(val string) {
	s.Message = val
}

func (*ApiErrorAuthError) listJobRes() {}
func (*ApiErrorAuthError) pingRes()    {}

// Ref: #/components/schemas/ApiErrorGenericError
type ApiErrorGenericError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiErrorGenericError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiErrorGenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiErrorGenericError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiErrorGenericError) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/Job
type Job struct {
	// Job name.
	Name OptString `json:"name"`
	// Job script.
	Script OptString `json:"script"`
}

// GetName returns the value of Name.
func (s *Job) GetName() OptString {
	return s.Name
}

// GetScript returns the value of Script.
func (s *Job) GetScript() OptString {
	return s.Script
}

// SetName sets the value of Name.
func (s *Job) SetName(val OptString) {
	s.Name = val
}

// SetScript sets the value of Script.
func (s *Job) SetScript(val OptString) {
	s.Script = val
}

type ListJobBadRequest ApiErrorGenericError

func (*ListJobBadRequest) listJobRes() {}

type ListJobInternalServerError ApiErrorGenericError

func (*ListJobInternalServerError) listJobRes() {}

// Ref: #/components/schemas/ListJobResponse
type ListJobResponse struct {
	// Bucket name.
	Jobs []Job `json:"jobs"`
}

// GetJobs returns the value of Jobs.
func (s *ListJobResponse) GetJobs() []Job {
	return s.Jobs
}

// SetJobs sets the value of Jobs.
func (s *ListJobResponse) SetJobs(val []Job) {
	s.Jobs = val
}

func (*ListJobResponse) listJobRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PingBadRequest ApiErrorGenericError

func (*PingBadRequest) pingRes() {}

type PingInternalServerError ApiErrorGenericError

func (*PingInternalServerError) pingRes() {}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	// Ping response.
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingResponse) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingResponse) SetMessage(val OptString) {
	s.Message = val
}

func (*PingResponse) pingRes() {}
