// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListJob implements ListJob operation.
//
// List jobs.
//
// GET /api/job
func (UnimplementedHandler) ListJob(ctx context.Context) (r ListJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements Ping operation.
//
// Ping server.
//
// GET /api/ping
func (UnimplementedHandler) Ping(ctx context.Context, params PingParams) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}
