// Code generated by ogen, DO NOT EDIT.
package api

type JobDetailRes interface {
	jobDetailRes()
}

type ListJobRes interface {
	listJobRes()
}

type PingRes interface {
	pingRes()
}

type RunJobRes interface {
	runJobRes()
}
