// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/ApiErrorAuthError
type ApiErrorAuthError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiErrorAuthError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiErrorAuthError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiErrorAuthError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiErrorAuthError) SetMessage(val string) {
	s.Message = val
}

func (*ApiErrorAuthError) jobDetailRes() {}
func (*ApiErrorAuthError) jobOutputRes() {}
func (*ApiErrorAuthError) listJobRes()   {}
func (*ApiErrorAuthError) pingRes()      {}
func (*ApiErrorAuthError) runJobRes()    {}

// Ref: #/components/schemas/ApiErrorGenericError
type ApiErrorGenericError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiErrorGenericError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiErrorGenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiErrorGenericError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiErrorGenericError) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/Job
type Job struct {
	// Job id.
	Jid OptString `json:"jid"`
	// Run id.
	LatestRunid OptString `json:"latest_runid"`
	// Number of steps.
	StepCount OptInt32 `json:"step_count"`
	// Last run exit code.
	Exitcode OptInt32 `json:"exitcode"`
}

// GetJid returns the value of Jid.
func (s *Job) GetJid() OptString {
	return s.Jid
}

// GetLatestRunid returns the value of LatestRunid.
func (s *Job) GetLatestRunid() OptString {
	return s.LatestRunid
}

// GetStepCount returns the value of StepCount.
func (s *Job) GetStepCount() OptInt32 {
	return s.StepCount
}

// GetExitcode returns the value of Exitcode.
func (s *Job) GetExitcode() OptInt32 {
	return s.Exitcode
}

// SetJid sets the value of Jid.
func (s *Job) SetJid(val OptString) {
	s.Jid = val
}

// SetLatestRunid sets the value of LatestRunid.
func (s *Job) SetLatestRunid(val OptString) {
	s.LatestRunid = val
}

// SetStepCount sets the value of StepCount.
func (s *Job) SetStepCount(val OptInt32) {
	s.StepCount = val
}

// SetExitcode sets the value of Exitcode.
func (s *Job) SetExitcode(val OptInt32) {
	s.Exitcode = val
}

type JobDetailBadRequest ApiErrorGenericError

func (*JobDetailBadRequest) jobDetailRes() {}

type JobDetailInternalServerError ApiErrorGenericError

func (*JobDetailInternalServerError) jobDetailRes() {}

// Ref: #/components/schemas/JobDetailResponse
type JobDetailResponse struct {
	Job OptJob `json:"job"`
	Run OptRun `json:"run"`
	// Job output file path.
	OutputFile OptString `json:"output_file"`
	// Job output.
	Output OptString `json:"output"`
}

// GetJob returns the value of Job.
func (s *JobDetailResponse) GetJob() OptJob {
	return s.Job
}

// GetRun returns the value of Run.
func (s *JobDetailResponse) GetRun() OptRun {
	return s.Run
}

// GetOutputFile returns the value of OutputFile.
func (s *JobDetailResponse) GetOutputFile() OptString {
	return s.OutputFile
}

// GetOutput returns the value of Output.
func (s *JobDetailResponse) GetOutput() OptString {
	return s.Output
}

// SetJob sets the value of Job.
func (s *JobDetailResponse) SetJob(val OptJob) {
	s.Job = val
}

// SetRun sets the value of Run.
func (s *JobDetailResponse) SetRun(val OptRun) {
	s.Run = val
}

// SetOutputFile sets the value of OutputFile.
func (s *JobDetailResponse) SetOutputFile(val OptString) {
	s.OutputFile = val
}

// SetOutput sets the value of Output.
func (s *JobDetailResponse) SetOutput(val OptString) {
	s.Output = val
}

func (*JobDetailResponse) jobDetailRes() {}

type JobOutputBadRequest ApiErrorGenericError

func (*JobOutputBadRequest) jobOutputRes() {}

type JobOutputInternalServerError ApiErrorGenericError

func (*JobOutputInternalServerError) jobOutputRes() {}

// Ref: #/components/schemas/JobOutputResponse
type JobOutputResponse struct {
	// Job output.
	Output OptString `json:"output"`
}

// GetOutput returns the value of Output.
func (s *JobOutputResponse) GetOutput() OptString {
	return s.Output
}

// SetOutput sets the value of Output.
func (s *JobOutputResponse) SetOutput(val OptString) {
	s.Output = val
}

func (*JobOutputResponse) jobOutputRes() {}

type ListJobBadRequest ApiErrorGenericError

func (*ListJobBadRequest) listJobRes() {}

type ListJobInternalServerError ApiErrorGenericError

func (*ListJobInternalServerError) listJobRes() {}

// Ref: #/components/schemas/ListJobResponse
type ListJobResponse struct {
	// Bucket name.
	Jobs []Job `json:"jobs"`
}

// GetJobs returns the value of Jobs.
func (s *ListJobResponse) GetJobs() []Job {
	return s.Jobs
}

// SetJobs sets the value of Jobs.
func (s *ListJobResponse) SetJobs(val []Job) {
	s.Jobs = val
}

func (*ListJobResponse) listJobRes() {}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptJob returns new OptJob with value set to v.
func NewOptJob(v Job) OptJob {
	return OptJob{
		Value: v,
		Set:   true,
	}
}

// OptJob is optional Job.
type OptJob struct {
	Value Job
	Set   bool
}

// IsSet returns true if OptJob was set.
func (o OptJob) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptJob) Reset() {
	var v Job
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptJob) SetTo(v Job) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptJob) Get() (v Job, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptJob) Or(d Job) Job {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRun returns new OptRun with value set to v.
func NewOptRun(v Run) OptRun {
	return OptRun{
		Value: v,
		Set:   true,
	}
}

// OptRun is optional Run.
type OptRun struct {
	Value Run
	Set   bool
}

// IsSet returns true if OptRun was set.
func (o OptRun) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRun) Reset() {
	var v Run
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRun) SetTo(v Run) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRun) Get() (v Run, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRun) Or(d Run) Run {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRunGlobals returns new OptRunGlobals with value set to v.
func NewOptRunGlobals(v RunGlobals) OptRunGlobals {
	return OptRunGlobals{
		Value: v,
		Set:   true,
	}
}

// OptRunGlobals is optional RunGlobals.
type OptRunGlobals struct {
	Value RunGlobals
	Set   bool
}

// IsSet returns true if OptRunGlobals was set.
func (o OptRunGlobals) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRunGlobals) Reset() {
	var v RunGlobals
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRunGlobals) SetTo(v RunGlobals) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRunGlobals) Get() (v RunGlobals, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRunGlobals) Or(d RunGlobals) RunGlobals {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRunSteps returns new OptRunSteps with value set to v.
func NewOptRunSteps(v RunSteps) OptRunSteps {
	return OptRunSteps{
		Value: v,
		Set:   true,
	}
}

// OptRunSteps is optional RunSteps.
type OptRunSteps struct {
	Value RunSteps
	Set   bool
}

// IsSet returns true if OptRunSteps was set.
func (o OptRunSteps) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRunSteps) Reset() {
	var v RunSteps
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRunSteps) SetTo(v RunSteps) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRunSteps) Get() (v RunSteps, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRunSteps) Or(d RunSteps) RunSteps {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PingBadRequest ApiErrorGenericError

func (*PingBadRequest) pingRes() {}

type PingInternalServerError ApiErrorGenericError

func (*PingInternalServerError) pingRes() {}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	// Ping response.
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingResponse) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingResponse) SetMessage(val OptString) {
	s.Message = val
}

func (*PingResponse) pingRes() {}

// Ref: #/components/schemas/Run
type Run struct {
	// Run id.
	Runid   OptString     `json:"runid"`
	Globals OptRunGlobals `json:"globals"`
	Steps   OptRunSteps   `json:"steps"`
}

// GetRunid returns the value of Runid.
func (s *Run) GetRunid() OptString {
	return s.Runid
}

// GetGlobals returns the value of Globals.
func (s *Run) GetGlobals() OptRunGlobals {
	return s.Globals
}

// GetSteps returns the value of Steps.
func (s *Run) GetSteps() OptRunSteps {
	return s.Steps
}

// SetRunid sets the value of Runid.
func (s *Run) SetRunid(val OptString) {
	s.Runid = val
}

// SetGlobals sets the value of Globals.
func (s *Run) SetGlobals(val OptRunGlobals) {
	s.Globals = val
}

// SetSteps sets the value of Steps.
func (s *Run) SetSteps(val OptRunSteps) {
	s.Steps = val
}

type RunGlobals map[string]string

func (s *RunGlobals) init() RunGlobals {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type RunJobBadRequest ApiErrorGenericError

func (*RunJobBadRequest) runJobRes() {}

type RunJobInternalServerError ApiErrorGenericError

func (*RunJobInternalServerError) runJobRes() {}

// Ref: #/components/schemas/RunJobRequest
type RunJobRequest struct {
	// Job id.
	Jobid OptString `json:"jobid"`
}

// GetJobid returns the value of Jobid.
func (s *RunJobRequest) GetJobid() OptString {
	return s.Jobid
}

// SetJobid sets the value of Jobid.
func (s *RunJobRequest) SetJobid(val OptString) {
	s.Jobid = val
}

// Ref: #/components/schemas/RunJobResponse
type RunJobResponse struct {
	// Job status.
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *RunJobResponse) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *RunJobResponse) SetMessage(val OptString) {
	s.Message = val
}

func (*RunJobResponse) runJobRes() {}

type RunJobUnauthorized ApiErrorGenericError

func (*RunJobUnauthorized) runJobRes() {}

type RunSteps map[string]string

func (s *RunSteps) init() RunSteps {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}
