// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// JobDetail implements JobDetail operation.
//
// Get job detail.
//
// GET /api/job/detail
func (UnimplementedHandler) JobDetail(ctx context.Context, params JobDetailParams) (r JobDetailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// JobOutput implements JobOutput operation.
//
// Get job output.
//
// GET /api/job/output
func (UnimplementedHandler) JobOutput(ctx context.Context, params JobOutputParams) (r JobOutputRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListJob implements ListJob operation.
//
// List jobs.
//
// GET /api/job
func (UnimplementedHandler) ListJob(ctx context.Context) (r ListJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements Ping operation.
//
// Ping server.
//
// GET /api/ping
func (UnimplementedHandler) Ping(ctx context.Context, params PingParams) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RunJob implements RunJob operation.
//
// Run a job.
//
// POST /api/job/run
func (UnimplementedHandler) RunJob(ctx context.Context, req *RunJobRequest) (r RunJobRes, _ error) {
	return r, ht.ErrNotImplemented
}
